In [2]:
# Importing the necessary packages
import numpy as np                                  # "Scientific computing"
import scipy.stats as stats                         # Statistical tests

import pandas as pd                                 # Data Frame
from pandas.api.types import CategoricalDtype

import matplotlib.pyplot as plt                     # Basic visualisation
from statsmodels.graphics.mosaicplot import mosaic  # Mosaic diagram
import seaborn as sns                               # Advanced data visualisation

In [3]:
df = pd.read_csv('C:\DSAI_2021-22\Voorbereiding_Examen\hypothesetesten\dagen.csv')
df

    Days
0     22
1     24
2     18
3     27
4     21
5     18
6     20
7     14
8     22
9     32
10    31
11    27
12    31
13    17
14    22
15    29
16    21
17    29
18    31
19    21
20    27
21    22
22    22
23    16
24    30
25    21
26    24
27    18
28    18
29    18
30    21
31    19
32    33
33    33
34    25
35    28
36    34
37    31
38    27
39    19
40    27
41    18
42    31
43    30
44    31
45    25
46    32
47    32
48    26
49    30

In [5]:
# variabelen aanmaken voor alle gegevens
# Properties of the sample:
n = df.Days.shape[0]      # sample size
sm = df.Days  # sample mean
s = 0.55    # population standard deviation (assumed to be known)
a = 0.05    # significance level (chosen by the researcher)
m0 = 3.3    # hypothetical population mean (H0)