# Lab 1.01 - Australian Athletes (ais)

## Korte intro-oefeningen

In [2]:
# Nodige libraries importeren.
import numpy as np
import pandas as pd

Een dataframe ophalen doe je met de functie 'read_csv' van Pandas. Kopieer de link van de bron en plak deze tussen ronde haken.
Als de bron van Github komt, let op dat je zeker de 'raw' versie ervan kopieert. Dit merk je op bij vooraan 'raw' in de URL te zien.

De eerste (vijf) rijen van een dataframe tonen doe je aan de hand van head(). De laatste doe je met tail(). Je kan het aantal rijen specifiÃ«ren door dit mee te geven als parameter.

In [3]:
ais = pd.read_csv('https://raw.githubusercontent.com/HoGentTIN/dsai-en-labs/main/data/ais.csv')
ais.head()
ais.tail()

,id,rcc,wcc,hc,hg,ferr,bmi,ssf,pcBfat,lbm,ht,wt,sex,sport
197,198,4.90,7.6,45.6,16.0,90,27.56,67.2,11.79,82.0,183.9,93.2,m,W_Polo
198,199,5.66,8.3,50.2,17.7,38,23.76,56.5,10.05,72.0,183.5,80.0,m,Tennis
199,200,5.03,6.4,42.7,14.3,122,22.01,47.6,8.51,68.0,183.1,73.8,m,Tennis
200,201,4.97,8.8,43.0,14.9,233,22.34,60.4,11.50,63.0,178.4,71.1,m,Tennis
201,202,5.38,6.3,46.0,15.7,32,21.07,34.9,6.26,72.0,190.8,76.7,m,Tennis

Toon algemene informatie over de dataset.

* Shape geeft je een tupel terug van twee waarden: het aantal rijen en het aantal kolommen.
* Dtypes geeft je de datatype van ieder variabele terug.
* Describe gaat algemene informatie geven over ieder variabele.
* Value_counts telt het aantal voorkomens van waarden in een dataset. Met deze functie kan je een frequentietabel opbouwen.

In [4]:
rijen = ais.shape[0]
kolommen = ais.shape[1]
print(f'Deze dataset bestaat uit {rijen} rijen en {kolommen} kolommen.')

typeVar = ais.dtypes

algemeneInfo = ais.describe

# Het aantal kolommen van ieder type opvragen.
# Vraag eerst op wat de datatypes zijn van iedere kolom met dtypes
# Bereken hierop het aantal voorkomens met value_counts
ais.dtypes.value_counts()

Deze dataset bestaat uit 202 rijen en 14 kolommen.

float64    10
int64       2
object      2
dtype: int64

ID is de index van de dataset. Dit moeten wij nog instellen door middel van .set_index(..naam van de kolom..)
Let op! Deze methode is immutable en past de dataset niet aan. Spreek de methode aan en sla de dataset op zoals hieronder.

In [4]:
ais = ais.set_index('id')

Sommige kwalitatieve variabelen worden nog opgeslaan onder een 'object' type. Dit mag niet en we moeten dit aanpassen naar een categorische variabele. Om een kolom op te halen zijn er twee mogelijkheden. Ofwel doe je .kolomnaam ofwel gebruik je vierkante haakjes met daartussen de kolomnaam.

Een datatype omzetten doe je met 'astype'. Dit is een immutable methode dus sla deze nieuwe dataset op of overschrijf de huidige dataset zoals hieronder.

In [5]:
ais.sex = ais.sex.astype('category')

# Alternatieve manier.
ais['sex'] = ais['sex'].astype('category')

Een omschrijving geven van de ferr, bmi en sex kolommen kan je vlug doen met de describe methode.

In [9]:
ais['ferr'].describe()

count    202.000000
mean      76.876238
std       47.501239
min        8.000000
25%       41.250000
50%       65.500000
75%       97.000000
max      234.000000
Name: ferr, dtype: float64

In [7]:
ais['bmi'].describe()

count    202.000000
mean      22.955891
std        2.863933
min       16.750000
25%       21.082500
50%       22.720000
75%       24.465000
max       34.420000
Name: bmi, dtype: float64

In [6]:
ais['sex'].describe()

count     202
unique      2
top         m
freq      102
Name: sex, dtype: object

## Oefeningen

In [ ]:
# Tweede rij van de dataset
# OPM: gebruik [[...]] voor een dataframe en [...] voor een serie
ais.iloc[[2]]

# Rij vier tot en met zes
# bouw eerst een filter op --> ais['id'].isin([4,5,6])
# vraag dan alles van de dataset op die voldoet aan de filter --> ais[filter]
ais[ais['id'].isin([4,5,6])]

# Kolom zes tot en met acht.
# gebruik .loc[:, ['kolom1', 'kolom2', ... ]] om een specifiek aantal kolommen op te vragen
# voor Ã©Ã©n kolom kan je het houden bij ais['kolom'] of ais.kolom
ais.loc[:, ['ferr', 'bmi', 'ssf']]

# De variabele pcBfat
# Verschillende manieren om een kolom op te halen:
ais['pcBfat']
ais.pcBfat
ais.loc[:, 'pcBfat']

# Alles voor de sport 'netball'
# maak eerst een filter op --> ais['sport'] == 'Netball'
ais[ais['sport'] == 'Netball']


# Enkel de kolom 'wt' voor netball-spelers
# ais['kolom'][filter]
ais['wt'][ais['sport'] == 'Netball']

# Alternatieve manier. Hier kan je efficiÃ«nt de filters aanpassen in grote python documenten.
kolom = 'wt'
filter = ais['sport'] == 'Netball'
ais[kolom][filter]

# Welke atleten hebben een bmi groter dan 26?
# voorzie een lijst van alle unieke waarden
# voorzie een frequentietabel van hoe vaak een sport voorkomt
filter = ais['bmi'] > 26
kolom = 'sport'

ais[kolom][filter].unique # alle unieke kolommen
ais[kolom][filter].value_counts() # frequentietabel

<bound method Series.unique of 52     Netball
69       Field
70       Field
71       Field
72       Field
74       Field
109       Swim
112       Swim
121        Row
124        Row
144      Field
145      Field
159      Field
161      Field
162      Field
175    T_Sprnt
177      Field
178      Field
191     W_Polo
195     W_Polo
197     W_Polo
Name: sport, dtype: object>

Field      12
W_Polo      3
Swim        2
Row         2
Netball     1
T_Sprnt     1
Name: sport, dtype: int64