# Lab 1.02 - Android Persistence

Je hebt enkel Pandas nodig. Importeer de dataset. Bekijk het CSV-bestand zeker nog eens om te kijken hoe alle waarden gescheiden zijn. In dit geval worden alle waarden gescheiden door een puntkomma. Geef dit mee als 'delimiter' parameter.

In [1]:
import pandas as pd
ap = pd.read_csv('https://raw.githubusercontent.com/HoGentTIN/dsai-en-labs/main/data/android_persistence_cpu.csv', delimiter=';')
ap

      Time    PersistenceType DataSize
0     1.81  Sharedpreferences    Small
1     1.35  Sharedpreferences    Small
2     1.84  Sharedpreferences    Small
3     1.54  Sharedpreferences    Small
4     1.81  Sharedpreferences    Small
..     ...                ...      ...
295  12.12              Realm    Large
296  10.85              Realm    Large
297  12.32              Realm    Large
298  12.04              Realm    Large
299  10.53              Realm    Large

[300 rows x 3 columns]

1. Print het aantal rijen en kolommen uit.
2. Verander de kolommen met een object-type naar het meest passende type.
3. Geef info over de gehele dataset.
4. Toon alle datatypes van de dataset.

In [2]:
# Print het aantal rijen en kolommen uit.
print(f'De dataset bevat {ap.shape[0]} rijen & {ap.shape[1]} kolommen ')

# PType en DataSize zijn twee kwalitatieve waarden die nu worden gezien als een 'object'. Vorm de twee kolommen om naar een categorietype. 
ap['PersistenceType'] = ap['PersistenceType'].astype('category')
ap['DataSize'] = ap['DataSize'].astype('category')

# Geef info over de dataset.
ap.info()

# Toon alle datatypes van de dataset.
ap.dtypes

De dataset bevat 300 rijen & 3 kolommen
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Time             300 non-null    float64
 1   PersistenceType  300 non-null    category
 2   DataSize         300 non-null    category
dtypes: category(2), float64(1)
memory usage: 3.4 KB

Time                float64
PersistenceType    category
DataSize           category
dtype: object

1. Geef een omschrijving van iedere variabele in de dataset.
2. Bereken het gemiddelde van de Time-variabele. Hou rekening met niet-ingevulde velden.

In [5]:
# Toon de statistieken van iedere kolom. Hiervoor moet je iedere kolom 
ap['PersistenceType'].describe()
ap['Time'].describe()
ap['DataSize'].describe()


# Extra:
# Bereken het gemiddelde van de Time-variabele. Zorg ervoor dat ieder niet-ingevuld element wordt vervangen door het gemiddelde.
m = ap.Time.mean()
ap['Time'] = ap.Time.fillna(m)

1. Haal de unieke velden op van iedere categorische variabele. 
2. Vraag een frequentietabel op van beide variabelen.

In [8]:
# Unieke waarden
ap['PersistenceType'].unique()
ap['DataSize'].unique()

# Frequentietabel opvragen
ap['PersistenceType'].value_counts()
ap['DataSize'].value_counts()

Small     120
Large      90
Medium     90
Name: DataSize, dtype: int64

Opmerking: Crosstab komt pas in hoofdstuk 4 aan bod.

Met een kruistabel of contingency table toon je een mogelijk verband tussen een kwalitatieve en een kwantitatieve variabele. 
In dit geval is PersistenceType een categorische variabele. DataSize maakt gebruik van getallen en is hier de kwantitatieve variabele.
Crosstab verwacht twee parameters in dezelfde volgorde: de afhankelijke variabele en een onafhankelijke variabele.

In [ ]:
pd.crosstab(ap['PersistenceType'], ap['DataSize'])

DataSize           Large  Medium  Small
PersistenceType
GreenDAO              30      30     30
Realm                 30      30     30
SQLLite               30      30     30
Sharedpreferences      0       0     30